# Generated by Django 5.1.3 on 2024-12-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsmanagement', '0003_alter_ad_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='user_id',
            new_name='owner',
        ),
    ]
