# Generated by Django 5.1.3 on 2024-12-02 14:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsmanagement', '0005_rename_user_id_comment_owner_remove_comment_ad_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('ad', 'owner')},
        ),
    ]
